### ISSUE TITLE
Issue with filter_flag while using pyranges.read_bam

### ISSUE THREAD

**Issue by flatley176** [pyranges/bamread#1]
Hi, 

Thanks for this package, it's been super useful to my needs. Also hoping everyone is safe during these hard times.

I want to use pyranges to read in a bam file and do some downstream intersect calculations with a bed file. I wish to read in the entire bam file, however I note the `filter_flag` default is 1540, which excludes unmapped reads. I wish to include the unmapped read count stats in my calculations, so I tried `filter_flag = 1536` (so I exclude flag = 4, which refers to unmapped reads, [per the popular Broad Institute tool](https://broadinstitute.github.io/picard/explain-flags.html)) - but that doesn't work. Below is a code snippet which works when I exclude unmapped reads (flag = 1540, the default) but doesn't when I try to include them (flag = 1536).

```
>>> import pyranges
>>> import bamread
>>> bam_file = pyranges.read_bam(bamfile, filter_flag=1540)
>>> bam_file.df.shape
(19979065, 5)
>>> bam_file = pyranges.read_bam(bamfile, filter_flag=1536)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sradhakrishnan/venv/lib/python3.6/site-packages/pyranges/readers.py", line 190, in read_bam
    df = bamread.read_bam(f, mapq, required_flag, filter_flag)
  File "/home/sradhakrishnan/venv/lib/python3.6/site-packages/bamread/read.py", line 9, in read_bam
    f, mapq, required_flag, filter_flag)
  File "bamread/src/bamread.pyx", line 17, in bamread.src.bamread._bamread
    cpdef _bamread(filename, uint32_t mapq=0, uint64_t required_flag=0, uint64_t filter_flag=1540):
  File "bamread/src/bamread.pyx", line 69, in bamread.src.bamread._bamread
    end = a.reference_end
TypeError: an integer is required
```
Looking at the `.pyx` [file](https://github.com/pyranges/bamread/blob/master/bamread/src/bamread.pyx) in the bamread repo,  it looks in lines 21 and 22 that the `start` and `end` variables need to be integers - which is likely violated for unmapped reads that don't have coordinates? 

Are there any workarounds in my case where I can include unmapped reads in my calculations? 

If this is not possible, my fallback approach is to read in the bam file directly using `pysam.AlignmentFile` (and skip bamread for the unmapped read inclusion, while still using it to calculate intersection stats because that's really nice) but that's a little messy. Any help is highly appreciated!

Stay safe and thanks,
Srihari

**Comment by endrebak** [comment]
You are right. I am excluding unmapped reads; they have a value of `-1` IIRC. I could change bamread to include these. 

I do not use bams much myself, so I am going to need help from the community to get this package right. Thanks for the feedback! I will try to fix it today.

**Comment by endrebak** [comment]
Do you have an example bam I could test my fixes on btw? I do not have any available :/

**Comment by endrebak** [comment]
Actually, ignore that. I could just do `flag || 4` and if it is true, I'll set the starts and ends to -1.

**Comment by endrebak** [comment]
I just pushed `0.0.7`. Please report how it worked :)

**Comment by flatley176** [comment]
Sorry, morning's just getting rolled out where I am and things are starting to move :) 

I shall retest and get back to you today. Thanks for your super quick attention to this!

**Comment by flatley176** [comment]
Hi @endrebak - looks like that fixed it! Thanks a bunch!

```
>>> bam_file = pyranges.read_bam(bamfilepath, filter_flag=1540)
>>> bam_file.df.shape
(19979065, 5)
>>> bam_file = pyranges.read_bam(bamfilepath, filter_flag=1536)
>>> bam_file.df.shape
(21113400, 5)
```

**Comment by endrebak** [comment]
I am so happy it fixed it for you :) You are responsible for unaligned intervals, those with a -1 start and end. They might influence some operations :)

I think I should write a warning in the print string if a PyRanges contains unaligned intervals.

**Comment by endrebak** [comment]
Just out of curiosity (if you have the time to check) do the unaligned intervals have a chromosome?

**Comment by flatley176** [comment]
Writing a warning out makes sense. 

Typically in my bam files, I see a `*` in lieu of `chr` for unmapped reads. Was that what you were asking?

**Comment by endrebak** [comment]
Yes, thanks!
