### ISSUE TITLE
Strand information from flag

### ISSUE THREAD

**Issue by MuhammedHasan** [pyranges/bamread#6]
Hi, 

https://github.com/pyranges/bamread/blob/4b3d15b8796f848f9c2aa838be77d57d9455e63a/bamread/read.py#L14

This line should be like that, isn't it? 

```
strands = pd.Series(strands).replace({0: "+", 16: "-"}).astype("category")
```
flag 16 means that `SEQ being reverse complemented` so negative-strand?

https://en.wikipedia.org/wiki/SAM_(file_format)

**Comment by endrebak** [comment]
Have I made such a fundamental mistake? :(

**Comment by endrebak** [comment]
This [answer](https://www.biostars.org/p/59388/#59392) seems to agree with you:

> The bit for 16 is set if the read is mapped on the reverse strand

**Comment by endrebak** [comment]
Yikes, you are correct!

**Comment by endrebak** [comment]
Fixed and uploaded new version to PyPI.
